pre-commit:
  parallel: true
  commands:
    ruff-lint:
      glob: "*.py"
      run: uv run ruff check --fix {staged_files}
    ruff-format:
      glob: "*.py"
      run: uv run ruff format {staged_files}
    tombi-format:
      glob: "*.toml"
      run: uv run tombi format {staged_files}
    tombi-lint:
      glob: "*.toml"
      run: uv run tombi lint {staged_files}
    ty:
      glob: "src/**/*.py"
      run: uv run ty check {staged_files}
